name: app_database
description: "Database for the app"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  path: any
  drift: 2.24.0
  drift_flutter: 0.2.4

  # Logger
  l: 5.0.0

  # Utils
  uuid: 4.5.1
  path_provider: 2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: 2.24.0
  build_runner: 2.4.14
  sizzle_lints: 2.1.3
