name: daily_tasks
description: "A new Flutter project."
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

workspace:
#   - packages/rest_client
  - packages/app_database

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: any
  async: any
  meta: any
  intl: any

  # Routing
  octopus: ^0.0.9

  # State management
  control: ^0.2.0

  # Storing data
  shared_preferences: ^2.3.4

  # Logging
  # sentry_flutter: ^8.12.0
  stack_trace: 1.12.0

  # Utils
  clock: ^1.1.1
  package_info_plus: ^8.1.2

  # Packages
  app_database:
    path: packages/app_database

dev_dependencies:
  flutter_test:
    sdk: flutter
  sizzle_lints: ^2.1.3

  # Utils
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true
  generate: true
  # assets:
    # Add assets from the images directory to the application.
    # - assets/images/

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 120